#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSERVICE.LQTOSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITSERVICE")]
	public partial class Data_itservicesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertCONGVIEC(CONGVIEC instance);
    partial void UpdateCONGVIEC(CONGVIEC instance);
    partial void DeleteCONGVIEC(CONGVIEC instance);
    partial void InsertCTCV(CTCV instance);
    partial void UpdateCTCV(CTCV instance);
    partial void DeleteCTCV(CTCV instance);
    partial void InsertCTKTV(CTKTV instance);
    partial void UpdateCTKTV(CTKTV instance);
    partial void DeleteCTKTV(CTKTV instance);
    partial void InsertDANHMUC_YEUCAU(DANHMUC_YEUCAU instance);
    partial void UpdateDANHMUC_YEUCAU(DANHMUC_YEUCAU instance);
    partial void DeleteDANHMUC_YEUCAU(DANHMUC_YEUCAU instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertKITHUATVIEN(KITHUATVIEN instance);
    partial void UpdateKITHUATVIEN(KITHUATVIEN instance);
    partial void DeleteKITHUATVIEN(KITHUATVIEN instance);
    partial void InsertLINHVUC(LINHVUC instance);
    partial void UpdateLINHVUC(LINHVUC instance);
    partial void DeleteLINHVUC(LINHVUC instance);
    partial void InsertLOAI_YC(LOAI_YC instance);
    partial void UpdateLOAI_YC(LOAI_YC instance);
    partial void DeleteLOAI_YC(LOAI_YC instance);
    partial void InsertLOAITK(LOAITK instance);
    partial void UpdateLOAITK(LOAITK instance);
    partial void DeleteLOAITK(LOAITK instance);
    partial void InsertPHIEU_YC(PHIEU_YC instance);
    partial void UpdatePHIEU_YC(PHIEU_YC instance);
    partial void DeletePHIEU_YC(PHIEU_YC instance);
    partial void InsertPHIEUXACNHAN_YC(PHIEUXACNHAN_YC instance);
    partial void UpdatePHIEUXACNHAN_YC(PHIEUXACNHAN_YC instance);
    partial void DeletePHIEUXACNHAN_YC(PHIEUXACNHAN_YC instance);
    partial void InsertTINHTRANG_XN(TINHTRANG_XN instance);
    partial void UpdateTINHTRANG_XN(TINHTRANG_XN instance);
    partial void DeleteTINHTRANG_XN(TINHTRANG_XN instance);
    partial void InsertTRANGTHAI_YC(TRANGTHAI_YC instance);
    partial void UpdateTRANGTHAI_YC(TRANGTHAI_YC instance);
    partial void DeleteTRANGTHAI_YC(TRANGTHAI_YC instance);
    #endregion
		
		public Data_itservicesDataContext() : 
				base(global::ITSERVICE.Properties.Settings.Default.ITSERVICEConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itservicesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itservicesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itservicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itservicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<CONGVIEC> CONGVIECs
		{
			get
			{
				return this.GetTable<CONGVIEC>();
			}
		}
		
		public System.Data.Linq.Table<CTCV> CTCVs
		{
			get
			{
				return this.GetTable<CTCV>();
			}
		}
		
		public System.Data.Linq.Table<CTKTV> CTKTVs
		{
			get
			{
				return this.GetTable<CTKTV>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUC_YEUCAU> DANHMUC_YEUCAUs
		{
			get
			{
				return this.GetTable<DANHMUC_YEUCAU>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<KITHUATVIEN> KITHUATVIENs
		{
			get
			{
				return this.GetTable<KITHUATVIEN>();
			}
		}
		
		public System.Data.Linq.Table<LINHVUC> LINHVUCs
		{
			get
			{
				return this.GetTable<LINHVUC>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_YC> LOAI_YCs
		{
			get
			{
				return this.GetTable<LOAI_YC>();
			}
		}
		
		public System.Data.Linq.Table<LOAITK> LOAITKs
		{
			get
			{
				return this.GetTable<LOAITK>();
			}
		}
		
		public System.Data.Linq.Table<PHIEU_YC> PHIEU_YCs
		{
			get
			{
				return this.GetTable<PHIEU_YC>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUXACNHAN_YC> PHIEUXACNHAN_YCs
		{
			get
			{
				return this.GetTable<PHIEUXACNHAN_YC>();
			}
		}
		
		public System.Data.Linq.Table<TINHTRANG_XN> TINHTRANG_XNs
		{
			get
			{
				return this.GetTable<TINHTRANG_XN>();
			}
		}
		
		public System.Data.Linq.Table<TRANGTHAI_YC> TRANGTHAI_YCs
		{
			get
			{
				return this.GetTable<TRANGTHAI_YC>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROC_KHACHHANG")]
		public ISingleResult<PROC_KHACHHANGResult> PROC_KHACHHANG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PROC_KHACHHANGResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LOGINNAME_AC;
		
		private string _PASSWORD_AC;
		
		private System.Nullable<int> _MALOAI_TK;
		
		private string _MAKH;
		
		private System.Nullable<bool> _HIENHANH_AC;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<LOAITK> _LOAITK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOGINNAME_ACChanging(string value);
    partial void OnLOGINNAME_ACChanged();
    partial void OnPASSWORD_ACChanging(string value);
    partial void OnPASSWORD_ACChanged();
    partial void OnMALOAI_TKChanging(System.Nullable<int> value);
    partial void OnMALOAI_TKChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnHIENHANH_ACChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_ACChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._LOAITK = default(EntityRef<LOAITK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGINNAME_AC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LOGINNAME_AC
		{
			get
			{
				return this._LOGINNAME_AC;
			}
			set
			{
				if ((this._LOGINNAME_AC != value))
				{
					this.OnLOGINNAME_ACChanging(value);
					this.SendPropertyChanging();
					this._LOGINNAME_AC = value;
					this.SendPropertyChanged("LOGINNAME_AC");
					this.OnLOGINNAME_ACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_AC", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string PASSWORD_AC
		{
			get
			{
				return this._PASSWORD_AC;
			}
			set
			{
				if ((this._PASSWORD_AC != value))
				{
					this.OnPASSWORD_ACChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_AC = value;
					this.SendPropertyChanged("PASSWORD_AC");
					this.OnPASSWORD_ACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI_TK", DbType="Int")]
		public System.Nullable<int> MALOAI_TK
		{
			get
			{
				return this._MALOAI_TK;
			}
			set
			{
				if ((this._MALOAI_TK != value))
				{
					if (this._LOAITK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAI_TKChanging(value);
					this.SendPropertyChanging();
					this._MALOAI_TK = value;
					this.SendPropertyChanged("MALOAI_TK");
					this.OnMALOAI_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15)")]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_AC", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_AC
		{
			get
			{
				return this._HIENHANH_AC;
			}
			set
			{
				if ((this._HIENHANH_AC != value))
				{
					this.OnHIENHANH_ACChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_AC = value;
					this.SendPropertyChanged("HIENHANH_AC");
					this.OnHIENHANH_ACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_ACCOUNT", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.ACCOUNTs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.ACCOUNTs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITK_ACCOUNT", Storage="_LOAITK", ThisKey="MALOAI_TK", OtherKey="MALOAI_TK", IsForeignKey=true)]
		public LOAITK LOAITK
		{
			get
			{
				return this._LOAITK.Entity;
			}
			set
			{
				LOAITK previousValue = this._LOAITK.Entity;
				if (((previousValue != value) 
							|| (this._LOAITK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITK.Entity = null;
						previousValue.ACCOUNTs.Remove(this);
					}
					this._LOAITK.Entity = value;
					if ((value != null))
					{
						value.ACCOUNTs.Add(this);
						this._MALOAI_TK = value.MALOAI_TK;
					}
					else
					{
						this._MALOAI_TK = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAITK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACHUCVU;
		
		private string _TENCHUCVU;
		
		private string _MOTA_CHUCVU;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCVUChanging(string value);
    partial void OnMACHUCVUChanged();
    partial void OnTENCHUCVUChanging(string value);
    partial void OnTENCHUCVUChanged();
    partial void OnMOTA_CHUCVUChanging(string value);
    partial void OnMOTA_CHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this.OnTENCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCVU = value;
					this.SendPropertyChanged("TENCHUCVU");
					this.OnTENCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_CHUCVU", DbType="NVarChar(200)")]
		public string MOTA_CHUCVU
		{
			get
			{
				return this._MOTA_CHUCVU;
			}
			set
			{
				if ((this._MOTA_CHUCVU != value))
				{
					this.OnMOTA_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MOTA_CHUCVU = value;
					this.SendPropertyChanged("MOTA_CHUCVU");
					this.OnMOTA_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MACHUCVU", OtherKey="MACHUCVU")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGVIEC")]
	public partial class CONGVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACONGVIEC;
		
		private string _TENCONGVIEC;
		
		private System.Nullable<bool> _HIENHANH_CONGVIEC;
		
		private EntitySet<CTCV> _CTCVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACONGVIECChanging(string value);
    partial void OnMACONGVIECChanged();
    partial void OnTENCONGVIECChanging(string value);
    partial void OnTENCONGVIECChanged();
    partial void OnHIENHANH_CONGVIECChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_CONGVIECChanged();
    #endregion
		
		public CONGVIEC()
		{
			this._CTCVs = new EntitySet<CTCV>(new Action<CTCV>(this.attach_CTCVs), new Action<CTCV>(this.detach_CTCVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACONGVIEC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACONGVIEC
		{
			get
			{
				return this._MACONGVIEC;
			}
			set
			{
				if ((this._MACONGVIEC != value))
				{
					this.OnMACONGVIECChanging(value);
					this.SendPropertyChanging();
					this._MACONGVIEC = value;
					this.SendPropertyChanged("MACONGVIEC");
					this.OnMACONGVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCONGVIEC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENCONGVIEC
		{
			get
			{
				return this._TENCONGVIEC;
			}
			set
			{
				if ((this._TENCONGVIEC != value))
				{
					this.OnTENCONGVIECChanging(value);
					this.SendPropertyChanging();
					this._TENCONGVIEC = value;
					this.SendPropertyChanged("TENCONGVIEC");
					this.OnTENCONGVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_CONGVIEC", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_CONGVIEC
		{
			get
			{
				return this._HIENHANH_CONGVIEC;
			}
			set
			{
				if ((this._HIENHANH_CONGVIEC != value))
				{
					this.OnHIENHANH_CONGVIECChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_CONGVIEC = value;
					this.SendPropertyChanged("HIENHANH_CONGVIEC");
					this.OnHIENHANH_CONGVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CTCV", Storage="_CTCVs", ThisKey="MACONGVIEC", OtherKey="MACONGVIEC")]
		public EntitySet<CTCV> CTCVs
		{
			get
			{
				return this._CTCVs;
			}
			set
			{
				this._CTCVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTCVs(CTCV entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = this;
		}
		
		private void detach_CTCVs(CTCV entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTCV")]
	public partial class CTCV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPYC;
		
		private string _MACONGVIEC;
		
		private System.DateTime _THOIGIAN_THUCHIEN;
		
		private System.Nullable<bool> _HIENHANH_CTCV;
		
		private EntityRef<CONGVIEC> _CONGVIEC;
		
		private EntityRef<PHIEU_YC> _PHIEU_YC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPYCChanging(string value);
    partial void OnMAPYCChanged();
    partial void OnMACONGVIECChanging(string value);
    partial void OnMACONGVIECChanged();
    partial void OnTHOIGIAN_THUCHIENChanging(System.DateTime value);
    partial void OnTHOIGIAN_THUCHIENChanged();
    partial void OnHIENHANH_CTCVChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_CTCVChanged();
    #endregion
		
		public CTCV()
		{
			this._CONGVIEC = default(EntityRef<CONGVIEC>);
			this._PHIEU_YC = default(EntityRef<PHIEU_YC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPYC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPYC
		{
			get
			{
				return this._MAPYC;
			}
			set
			{
				if ((this._MAPYC != value))
				{
					if (this._PHIEU_YC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPYCChanging(value);
					this.SendPropertyChanging();
					this._MAPYC = value;
					this.SendPropertyChanged("MAPYC");
					this.OnMAPYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACONGVIEC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACONGVIEC
		{
			get
			{
				return this._MACONGVIEC;
			}
			set
			{
				if ((this._MACONGVIEC != value))
				{
					if (this._CONGVIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACONGVIECChanging(value);
					this.SendPropertyChanging();
					this._MACONGVIEC = value;
					this.SendPropertyChanged("MACONGVIEC");
					this.OnMACONGVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN_THUCHIEN", DbType="DateTime NOT NULL")]
		public System.DateTime THOIGIAN_THUCHIEN
		{
			get
			{
				return this._THOIGIAN_THUCHIEN;
			}
			set
			{
				if ((this._THOIGIAN_THUCHIEN != value))
				{
					this.OnTHOIGIAN_THUCHIENChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN_THUCHIEN = value;
					this.SendPropertyChanged("THOIGIAN_THUCHIEN");
					this.OnTHOIGIAN_THUCHIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_CTCV", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_CTCV
		{
			get
			{
				return this._HIENHANH_CTCV;
			}
			set
			{
				if ((this._HIENHANH_CTCV != value))
				{
					this.OnHIENHANH_CTCVChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_CTCV = value;
					this.SendPropertyChanged("HIENHANH_CTCV");
					this.OnHIENHANH_CTCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CTCV", Storage="_CONGVIEC", ThisKey="MACONGVIEC", OtherKey="MACONGVIEC", IsForeignKey=true)]
		public CONGVIEC CONGVIEC
		{
			get
			{
				return this._CONGVIEC.Entity;
			}
			set
			{
				CONGVIEC previousValue = this._CONGVIEC.Entity;
				if (((previousValue != value) 
							|| (this._CONGVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGVIEC.Entity = null;
						previousValue.CTCVs.Remove(this);
					}
					this._CONGVIEC.Entity = value;
					if ((value != null))
					{
						value.CTCVs.Add(this);
						this._MACONGVIEC = value.MACONGVIEC;
					}
					else
					{
						this._MACONGVIEC = default(string);
					}
					this.SendPropertyChanged("CONGVIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEU_YC_CTCV", Storage="_PHIEU_YC", ThisKey="MAPYC", OtherKey="MAPYC", IsForeignKey=true)]
		public PHIEU_YC PHIEU_YC
		{
			get
			{
				return this._PHIEU_YC.Entity;
			}
			set
			{
				PHIEU_YC previousValue = this._PHIEU_YC.Entity;
				if (((previousValue != value) 
							|| (this._PHIEU_YC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEU_YC.Entity = null;
						previousValue.CTCVs.Remove(this);
					}
					this._PHIEU_YC.Entity = value;
					if ((value != null))
					{
						value.CTCVs.Add(this);
						this._MAPYC = value.MAPYC;
					}
					else
					{
						this._MAPYC = default(string);
					}
					this.SendPropertyChanged("PHIEU_YC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTKTV")]
	public partial class CTKTV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKTV;
		
		private string _MALV;
		
		private string _MOTA_NHOM_KTV;
		
		private EntityRef<KITHUATVIEN> _KITHUATVIEN;
		
		private EntityRef<LINHVUC> _LINHVUC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKTVChanging(string value);
    partial void OnMAKTVChanged();
    partial void OnMALVChanging(string value);
    partial void OnMALVChanged();
    partial void OnMOTA_NHOM_KTVChanging(string value);
    partial void OnMOTA_NHOM_KTVChanged();
    #endregion
		
		public CTKTV()
		{
			this._KITHUATVIEN = default(EntityRef<KITHUATVIEN>);
			this._LINHVUC = default(EntityRef<LINHVUC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKTV", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKTV
		{
			get
			{
				return this._MAKTV;
			}
			set
			{
				if ((this._MAKTV != value))
				{
					if (this._KITHUATVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKTVChanging(value);
					this.SendPropertyChanging();
					this._MAKTV = value;
					this.SendPropertyChanged("MAKTV");
					this.OnMAKTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALV", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALV
		{
			get
			{
				return this._MALV;
			}
			set
			{
				if ((this._MALV != value))
				{
					if (this._LINHVUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALVChanging(value);
					this.SendPropertyChanging();
					this._MALV = value;
					this.SendPropertyChanged("MALV");
					this.OnMALVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_NHOM_KTV", DbType="NVarChar(200)")]
		public string MOTA_NHOM_KTV
		{
			get
			{
				return this._MOTA_NHOM_KTV;
			}
			set
			{
				if ((this._MOTA_NHOM_KTV != value))
				{
					this.OnMOTA_NHOM_KTVChanging(value);
					this.SendPropertyChanging();
					this._MOTA_NHOM_KTV = value;
					this.SendPropertyChanged("MOTA_NHOM_KTV");
					this.OnMOTA_NHOM_KTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KITHUATVIEN_CTKTV", Storage="_KITHUATVIEN", ThisKey="MAKTV", OtherKey="MAKTV", IsForeignKey=true)]
		public KITHUATVIEN KITHUATVIEN
		{
			get
			{
				return this._KITHUATVIEN.Entity;
			}
			set
			{
				KITHUATVIEN previousValue = this._KITHUATVIEN.Entity;
				if (((previousValue != value) 
							|| (this._KITHUATVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KITHUATVIEN.Entity = null;
						previousValue.CTKTVs.Remove(this);
					}
					this._KITHUATVIEN.Entity = value;
					if ((value != null))
					{
						value.CTKTVs.Add(this);
						this._MAKTV = value.MAKTV;
					}
					else
					{
						this._MAKTV = default(string);
					}
					this.SendPropertyChanged("KITHUATVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LINHVUC_CTKTV", Storage="_LINHVUC", ThisKey="MALV", OtherKey="MALV", IsForeignKey=true)]
		public LINHVUC LINHVUC
		{
			get
			{
				return this._LINHVUC.Entity;
			}
			set
			{
				LINHVUC previousValue = this._LINHVUC.Entity;
				if (((previousValue != value) 
							|| (this._LINHVUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LINHVUC.Entity = null;
						previousValue.CTKTVs.Remove(this);
					}
					this._LINHVUC.Entity = value;
					if ((value != null))
					{
						value.CTKTVs.Add(this);
						this._MALV = value.MALV;
					}
					else
					{
						this._MALV = default(string);
					}
					this.SendPropertyChanged("LINHVUC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUC_YEUCAU")]
	public partial class DANHMUC_YEUCAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADMYC;
		
		private string _MALOAI_YC;
		
		private string _MALV;
		
		private string _TIEUDE_DMYC;
		
		private string _MOTA_DMYC;
		
		private System.Nullable<bool> _HIENHANH_DMYC;
		
		private EntitySet<PHIEU_YC> _PHIEU_YCs;
		
		private EntityRef<LINHVUC> _LINHVUC;
		
		private EntityRef<LOAI_YC> _LOAI_YC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADMYCChanging(string value);
    partial void OnMADMYCChanged();
    partial void OnMALOAI_YCChanging(string value);
    partial void OnMALOAI_YCChanged();
    partial void OnMALVChanging(string value);
    partial void OnMALVChanged();
    partial void OnTIEUDE_DMYCChanging(string value);
    partial void OnTIEUDE_DMYCChanged();
    partial void OnMOTA_DMYCChanging(string value);
    partial void OnMOTA_DMYCChanged();
    partial void OnHIENHANH_DMYCChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_DMYCChanged();
    #endregion
		
		public DANHMUC_YEUCAU()
		{
			this._PHIEU_YCs = new EntitySet<PHIEU_YC>(new Action<PHIEU_YC>(this.attach_PHIEU_YCs), new Action<PHIEU_YC>(this.detach_PHIEU_YCs));
			this._LINHVUC = default(EntityRef<LINHVUC>);
			this._LOAI_YC = default(EntityRef<LOAI_YC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADMYC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADMYC
		{
			get
			{
				return this._MADMYC;
			}
			set
			{
				if ((this._MADMYC != value))
				{
					this.OnMADMYCChanging(value);
					this.SendPropertyChanging();
					this._MADMYC = value;
					this.SendPropertyChanged("MADMYC");
					this.OnMADMYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI_YC", DbType="VarChar(15)")]
		public string MALOAI_YC
		{
			get
			{
				return this._MALOAI_YC;
			}
			set
			{
				if ((this._MALOAI_YC != value))
				{
					if (this._LOAI_YC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAI_YCChanging(value);
					this.SendPropertyChanging();
					this._MALOAI_YC = value;
					this.SendPropertyChanged("MALOAI_YC");
					this.OnMALOAI_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALV", DbType="VarChar(15)")]
		public string MALV
		{
			get
			{
				return this._MALV;
			}
			set
			{
				if ((this._MALV != value))
				{
					if (this._LINHVUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALVChanging(value);
					this.SendPropertyChanging();
					this._MALV = value;
					this.SendPropertyChanged("MALV");
					this.OnMALVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUDE_DMYC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TIEUDE_DMYC
		{
			get
			{
				return this._TIEUDE_DMYC;
			}
			set
			{
				if ((this._TIEUDE_DMYC != value))
				{
					this.OnTIEUDE_DMYCChanging(value);
					this.SendPropertyChanging();
					this._TIEUDE_DMYC = value;
					this.SendPropertyChanged("TIEUDE_DMYC");
					this.OnTIEUDE_DMYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_DMYC", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string MOTA_DMYC
		{
			get
			{
				return this._MOTA_DMYC;
			}
			set
			{
				if ((this._MOTA_DMYC != value))
				{
					this.OnMOTA_DMYCChanging(value);
					this.SendPropertyChanging();
					this._MOTA_DMYC = value;
					this.SendPropertyChanged("MOTA_DMYC");
					this.OnMOTA_DMYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_DMYC", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_DMYC
		{
			get
			{
				return this._HIENHANH_DMYC;
			}
			set
			{
				if ((this._HIENHANH_DMYC != value))
				{
					this.OnHIENHANH_DMYCChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_DMYC = value;
					this.SendPropertyChanged("HIENHANH_DMYC");
					this.OnHIENHANH_DMYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUC_YEUCAU_PHIEU_YC", Storage="_PHIEU_YCs", ThisKey="MADMYC", OtherKey="MADMYC")]
		public EntitySet<PHIEU_YC> PHIEU_YCs
		{
			get
			{
				return this._PHIEU_YCs;
			}
			set
			{
				this._PHIEU_YCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LINHVUC_DANHMUC_YEUCAU", Storage="_LINHVUC", ThisKey="MALV", OtherKey="MALV", IsForeignKey=true)]
		public LINHVUC LINHVUC
		{
			get
			{
				return this._LINHVUC.Entity;
			}
			set
			{
				LINHVUC previousValue = this._LINHVUC.Entity;
				if (((previousValue != value) 
							|| (this._LINHVUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LINHVUC.Entity = null;
						previousValue.DANHMUC_YEUCAUs.Remove(this);
					}
					this._LINHVUC.Entity = value;
					if ((value != null))
					{
						value.DANHMUC_YEUCAUs.Add(this);
						this._MALV = value.MALV;
					}
					else
					{
						this._MALV = default(string);
					}
					this.SendPropertyChanged("LINHVUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_YC_DANHMUC_YEUCAU", Storage="_LOAI_YC", ThisKey="MALOAI_YC", OtherKey="MALOAI_YC", IsForeignKey=true)]
		public LOAI_YC LOAI_YC
		{
			get
			{
				return this._LOAI_YC.Entity;
			}
			set
			{
				LOAI_YC previousValue = this._LOAI_YC.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_YC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_YC.Entity = null;
						previousValue.DANHMUC_YEUCAUs.Remove(this);
					}
					this._LOAI_YC.Entity = value;
					if ((value != null))
					{
						value.DANHMUC_YEUCAUs.Add(this);
						this._MALOAI_YC = value.MALOAI_YC;
					}
					else
					{
						this._MALOAI_YC = default(string);
					}
					this.SendPropertyChanged("LOAI_YC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUC_YEUCAU = this;
		}
		
		private void detach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUC_YEUCAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKH;
		
		private string _HOTEN_KH;
		
		private string _EMAIL_KH;
		
		private string _SODTH_KH;
		
		private string _MACHUCVU;
		
		private System.Nullable<bool> _HIENHANH_KH;
		
		private EntitySet<ACCOUNT> _ACCOUNTs;
		
		private EntitySet<PHIEU_YC> _PHIEU_YCs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnHOTEN_KHChanging(string value);
    partial void OnHOTEN_KHChanged();
    partial void OnEMAIL_KHChanging(string value);
    partial void OnEMAIL_KHChanged();
    partial void OnSODTH_KHChanging(string value);
    partial void OnSODTH_KHChanged();
    partial void OnMACHUCVUChanging(string value);
    partial void OnMACHUCVUChanged();
    partial void OnHIENHANH_KHChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_KHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._ACCOUNTs = new EntitySet<ACCOUNT>(new Action<ACCOUNT>(this.attach_ACCOUNTs), new Action<ACCOUNT>(this.detach_ACCOUNTs));
			this._PHIEU_YCs = new EntitySet<PHIEU_YC>(new Action<PHIEU_YC>(this.attach_PHIEU_YCs), new Action<PHIEU_YC>(this.detach_PHIEU_YCs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HOTEN_KH
		{
			get
			{
				return this._HOTEN_KH;
			}
			set
			{
				if ((this._HOTEN_KH != value))
				{
					this.OnHOTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_KH = value;
					this.SendPropertyChanged("HOTEN_KH");
					this.OnHOTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_KH
		{
			get
			{
				return this._EMAIL_KH;
			}
			set
			{
				if ((this._EMAIL_KH != value))
				{
					this.OnEMAIL_KHChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_KH = value;
					this.SendPropertyChanged("EMAIL_KH");
					this.OnEMAIL_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODTH_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SODTH_KH
		{
			get
			{
				return this._SODTH_KH;
			}
			set
			{
				if ((this._SODTH_KH != value))
				{
					this.OnSODTH_KHChanging(value);
					this.SendPropertyChanging();
					this._SODTH_KH = value;
					this.SendPropertyChanged("SODTH_KH");
					this.OnSODTH_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="VarChar(15)")]
		public string MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_KH", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_KH
		{
			get
			{
				return this._HIENHANH_KH;
			}
			set
			{
				if ((this._HIENHANH_KH != value))
				{
					this.OnHIENHANH_KHChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_KH = value;
					this.SendPropertyChanged("HIENHANH_KH");
					this.OnHIENHANH_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_ACCOUNT", Storage="_ACCOUNTs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this._ACCOUNTs;
			}
			set
			{
				this._ACCOUNTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEU_YC", Storage="_PHIEU_YCs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<PHIEU_YC> PHIEU_YCs
		{
			get
			{
				return this._PHIEU_YCs;
			}
			set
			{
				this._PHIEU_YCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_KHACHHANG", Storage="_CHUCVU", ThisKey="MACHUCVU", OtherKey="MACHUCVU", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._MACHUCVU = value.MACHUCVU;
					}
					else
					{
						this._MACHUCVU = default(string);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KITHUATVIEN")]
	public partial class KITHUATVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKTV;
		
		private string _HOTEN_KTV;
		
		private string _EMAIL_KTV;
		
		private string _SODTH_KTV;
		
		private System.Nullable<bool> _HIENHANH_KTV;
		
		private EntitySet<CTKTV> _CTKTVs;
		
		private EntitySet<PHIEU_YC> _PHIEU_YCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKTVChanging(string value);
    partial void OnMAKTVChanged();
    partial void OnHOTEN_KTVChanging(string value);
    partial void OnHOTEN_KTVChanged();
    partial void OnEMAIL_KTVChanging(string value);
    partial void OnEMAIL_KTVChanged();
    partial void OnSODTH_KTVChanging(string value);
    partial void OnSODTH_KTVChanged();
    partial void OnHIENHANH_KTVChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_KTVChanged();
    #endregion
		
		public KITHUATVIEN()
		{
			this._CTKTVs = new EntitySet<CTKTV>(new Action<CTKTV>(this.attach_CTKTVs), new Action<CTKTV>(this.detach_CTKTVs));
			this._PHIEU_YCs = new EntitySet<PHIEU_YC>(new Action<PHIEU_YC>(this.attach_PHIEU_YCs), new Action<PHIEU_YC>(this.detach_PHIEU_YCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKTV", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKTV
		{
			get
			{
				return this._MAKTV;
			}
			set
			{
				if ((this._MAKTV != value))
				{
					this.OnMAKTVChanging(value);
					this.SendPropertyChanging();
					this._MAKTV = value;
					this.SendPropertyChanged("MAKTV");
					this.OnMAKTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KTV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOTEN_KTV
		{
			get
			{
				return this._HOTEN_KTV;
			}
			set
			{
				if ((this._HOTEN_KTV != value))
				{
					this.OnHOTEN_KTVChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_KTV = value;
					this.SendPropertyChanged("HOTEN_KTV");
					this.OnHOTEN_KTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_KTV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL_KTV
		{
			get
			{
				return this._EMAIL_KTV;
			}
			set
			{
				if ((this._EMAIL_KTV != value))
				{
					this.OnEMAIL_KTVChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_KTV = value;
					this.SendPropertyChanged("EMAIL_KTV");
					this.OnEMAIL_KTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODTH_KTV", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SODTH_KTV
		{
			get
			{
				return this._SODTH_KTV;
			}
			set
			{
				if ((this._SODTH_KTV != value))
				{
					this.OnSODTH_KTVChanging(value);
					this.SendPropertyChanging();
					this._SODTH_KTV = value;
					this.SendPropertyChanged("SODTH_KTV");
					this.OnSODTH_KTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_KTV", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_KTV
		{
			get
			{
				return this._HIENHANH_KTV;
			}
			set
			{
				if ((this._HIENHANH_KTV != value))
				{
					this.OnHIENHANH_KTVChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_KTV = value;
					this.SendPropertyChanged("HIENHANH_KTV");
					this.OnHIENHANH_KTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KITHUATVIEN_CTKTV", Storage="_CTKTVs", ThisKey="MAKTV", OtherKey="MAKTV")]
		public EntitySet<CTKTV> CTKTVs
		{
			get
			{
				return this._CTKTVs;
			}
			set
			{
				this._CTKTVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KITHUATVIEN_PHIEU_YC", Storage="_PHIEU_YCs", ThisKey="MAKTV", OtherKey="MAKTV")]
		public EntitySet<PHIEU_YC> PHIEU_YCs
		{
			get
			{
				return this._PHIEU_YCs;
			}
			set
			{
				this._PHIEU_YCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTKTVs(CTKTV entity)
		{
			this.SendPropertyChanging();
			entity.KITHUATVIEN = this;
		}
		
		private void detach_CTKTVs(CTKTV entity)
		{
			this.SendPropertyChanging();
			entity.KITHUATVIEN = null;
		}
		
		private void attach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.KITHUATVIEN = this;
		}
		
		private void detach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.KITHUATVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LINHVUC")]
	public partial class LINHVUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALV;
		
		private string _TENLV;
		
		private System.Nullable<bool> _HIENHANH_LV;
		
		private EntitySet<CTKTV> _CTKTVs;
		
		private EntitySet<DANHMUC_YEUCAU> _DANHMUC_YEUCAUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALVChanging(string value);
    partial void OnMALVChanged();
    partial void OnTENLVChanging(string value);
    partial void OnTENLVChanged();
    partial void OnHIENHANH_LVChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_LVChanged();
    #endregion
		
		public LINHVUC()
		{
			this._CTKTVs = new EntitySet<CTKTV>(new Action<CTKTV>(this.attach_CTKTVs), new Action<CTKTV>(this.detach_CTKTVs));
			this._DANHMUC_YEUCAUs = new EntitySet<DANHMUC_YEUCAU>(new Action<DANHMUC_YEUCAU>(this.attach_DANHMUC_YEUCAUs), new Action<DANHMUC_YEUCAU>(this.detach_DANHMUC_YEUCAUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALV", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALV
		{
			get
			{
				return this._MALV;
			}
			set
			{
				if ((this._MALV != value))
				{
					this.OnMALVChanging(value);
					this.SendPropertyChanging();
					this._MALV = value;
					this.SendPropertyChanged("MALV");
					this.OnMALVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENLV
		{
			get
			{
				return this._TENLV;
			}
			set
			{
				if ((this._TENLV != value))
				{
					this.OnTENLVChanging(value);
					this.SendPropertyChanging();
					this._TENLV = value;
					this.SendPropertyChanged("TENLV");
					this.OnTENLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_LV", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_LV
		{
			get
			{
				return this._HIENHANH_LV;
			}
			set
			{
				if ((this._HIENHANH_LV != value))
				{
					this.OnHIENHANH_LVChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_LV = value;
					this.SendPropertyChanged("HIENHANH_LV");
					this.OnHIENHANH_LVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LINHVUC_CTKTV", Storage="_CTKTVs", ThisKey="MALV", OtherKey="MALV")]
		public EntitySet<CTKTV> CTKTVs
		{
			get
			{
				return this._CTKTVs;
			}
			set
			{
				this._CTKTVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LINHVUC_DANHMUC_YEUCAU", Storage="_DANHMUC_YEUCAUs", ThisKey="MALV", OtherKey="MALV")]
		public EntitySet<DANHMUC_YEUCAU> DANHMUC_YEUCAUs
		{
			get
			{
				return this._DANHMUC_YEUCAUs;
			}
			set
			{
				this._DANHMUC_YEUCAUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTKTVs(CTKTV entity)
		{
			this.SendPropertyChanging();
			entity.LINHVUC = this;
		}
		
		private void detach_CTKTVs(CTKTV entity)
		{
			this.SendPropertyChanging();
			entity.LINHVUC = null;
		}
		
		private void attach_DANHMUC_YEUCAUs(DANHMUC_YEUCAU entity)
		{
			this.SendPropertyChanging();
			entity.LINHVUC = this;
		}
		
		private void detach_DANHMUC_YEUCAUs(DANHMUC_YEUCAU entity)
		{
			this.SendPropertyChanging();
			entity.LINHVUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_YC")]
	public partial class LOAI_YC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAI_YC;
		
		private string _TENLOAI_YC;
		
		private string _MOTALOAI_YC;
		
		private EntitySet<DANHMUC_YEUCAU> _DANHMUC_YEUCAUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAI_YCChanging(string value);
    partial void OnMALOAI_YCChanged();
    partial void OnTENLOAI_YCChanging(string value);
    partial void OnTENLOAI_YCChanged();
    partial void OnMOTALOAI_YCChanging(string value);
    partial void OnMOTALOAI_YCChanged();
    #endregion
		
		public LOAI_YC()
		{
			this._DANHMUC_YEUCAUs = new EntitySet<DANHMUC_YEUCAU>(new Action<DANHMUC_YEUCAU>(this.attach_DANHMUC_YEUCAUs), new Action<DANHMUC_YEUCAU>(this.detach_DANHMUC_YEUCAUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI_YC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI_YC
		{
			get
			{
				return this._MALOAI_YC;
			}
			set
			{
				if ((this._MALOAI_YC != value))
				{
					this.OnMALOAI_YCChanging(value);
					this.SendPropertyChanging();
					this._MALOAI_YC = value;
					this.SendPropertyChanged("MALOAI_YC");
					this.OnMALOAI_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI_YC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENLOAI_YC
		{
			get
			{
				return this._TENLOAI_YC;
			}
			set
			{
				if ((this._TENLOAI_YC != value))
				{
					this.OnTENLOAI_YCChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI_YC = value;
					this.SendPropertyChanged("TENLOAI_YC");
					this.OnTENLOAI_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTALOAI_YC", DbType="NVarChar(200)")]
		public string MOTALOAI_YC
		{
			get
			{
				return this._MOTALOAI_YC;
			}
			set
			{
				if ((this._MOTALOAI_YC != value))
				{
					this.OnMOTALOAI_YCChanging(value);
					this.SendPropertyChanging();
					this._MOTALOAI_YC = value;
					this.SendPropertyChanged("MOTALOAI_YC");
					this.OnMOTALOAI_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_YC_DANHMUC_YEUCAU", Storage="_DANHMUC_YEUCAUs", ThisKey="MALOAI_YC", OtherKey="MALOAI_YC")]
		public EntitySet<DANHMUC_YEUCAU> DANHMUC_YEUCAUs
		{
			get
			{
				return this._DANHMUC_YEUCAUs;
			}
			set
			{
				this._DANHMUC_YEUCAUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHMUC_YEUCAUs(DANHMUC_YEUCAU entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_YC = this;
		}
		
		private void detach_DANHMUC_YEUCAUs(DANHMUC_YEUCAU entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_YC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITK")]
	public partial class LOAITK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAI_TK;
		
		private string _TENLOAI_TK;
		
		private EntitySet<ACCOUNT> _ACCOUNTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAI_TKChanging(int value);
    partial void OnMALOAI_TKChanged();
    partial void OnTENLOAI_TKChanging(string value);
    partial void OnTENLOAI_TKChanged();
    #endregion
		
		public LOAITK()
		{
			this._ACCOUNTs = new EntitySet<ACCOUNT>(new Action<ACCOUNT>(this.attach_ACCOUNTs), new Action<ACCOUNT>(this.detach_ACCOUNTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI_TK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAI_TK
		{
			get
			{
				return this._MALOAI_TK;
			}
			set
			{
				if ((this._MALOAI_TK != value))
				{
					this.OnMALOAI_TKChanging(value);
					this.SendPropertyChanging();
					this._MALOAI_TK = value;
					this.SendPropertyChanged("MALOAI_TK");
					this.OnMALOAI_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI_TK", DbType="NVarChar(100)")]
		public string TENLOAI_TK
		{
			get
			{
				return this._TENLOAI_TK;
			}
			set
			{
				if ((this._TENLOAI_TK != value))
				{
					this.OnTENLOAI_TKChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI_TK = value;
					this.SendPropertyChanged("TENLOAI_TK");
					this.OnTENLOAI_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITK_ACCOUNT", Storage="_ACCOUNTs", ThisKey="MALOAI_TK", OtherKey="MALOAI_TK")]
		public EntitySet<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this._ACCOUNTs;
			}
			set
			{
				this._ACCOUNTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.LOAITK = this;
		}
		
		private void detach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.LOAITK = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEU_YC")]
	public partial class PHIEU_YC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPYC;
		
		private string _TIEUDE_PYC;
		
		private System.DateTime _NGAYLAP_PYC;
		
		private string _MAKH;
		
		private string _MADMYC;
		
		private string _MATT_YC;
		
		private string _MATT_XN;
		
		private string _MAKTV;
		
		private string _MOTA_PYC;
		
		private string _GHICHU;
		
		private System.Nullable<bool> _HIENHANH_PYC;
		
		private EntitySet<CTCV> _CTCVs;
		
		private EntitySet<PHIEUXACNHAN_YC> _PHIEUXACNHAN_YCs;
		
		private EntityRef<DANHMUC_YEUCAU> _DANHMUC_YEUCAU;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<KITHUATVIEN> _KITHUATVIEN;
		
		private EntityRef<TINHTRANG_XN> _TINHTRANG_XN;
		
		private EntityRef<TRANGTHAI_YC> _TRANGTHAI_YC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPYCChanging(string value);
    partial void OnMAPYCChanged();
    partial void OnTIEUDE_PYCChanging(string value);
    partial void OnTIEUDE_PYCChanged();
    partial void OnNGAYLAP_PYCChanging(System.DateTime value);
    partial void OnNGAYLAP_PYCChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnMADMYCChanging(string value);
    partial void OnMADMYCChanged();
    partial void OnMATT_YCChanging(string value);
    partial void OnMATT_YCChanged();
    partial void OnMATT_XNChanging(string value);
    partial void OnMATT_XNChanged();
    partial void OnMAKTVChanging(string value);
    partial void OnMAKTVChanged();
    partial void OnMOTA_PYCChanging(string value);
    partial void OnMOTA_PYCChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnHIENHANH_PYCChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_PYCChanged();
    #endregion
		
		public PHIEU_YC()
		{
			this._CTCVs = new EntitySet<CTCV>(new Action<CTCV>(this.attach_CTCVs), new Action<CTCV>(this.detach_CTCVs));
			this._PHIEUXACNHAN_YCs = new EntitySet<PHIEUXACNHAN_YC>(new Action<PHIEUXACNHAN_YC>(this.attach_PHIEUXACNHAN_YCs), new Action<PHIEUXACNHAN_YC>(this.detach_PHIEUXACNHAN_YCs));
			this._DANHMUC_YEUCAU = default(EntityRef<DANHMUC_YEUCAU>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._KITHUATVIEN = default(EntityRef<KITHUATVIEN>);
			this._TINHTRANG_XN = default(EntityRef<TINHTRANG_XN>);
			this._TRANGTHAI_YC = default(EntityRef<TRANGTHAI_YC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPYC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPYC
		{
			get
			{
				return this._MAPYC;
			}
			set
			{
				if ((this._MAPYC != value))
				{
					this.OnMAPYCChanging(value);
					this.SendPropertyChanging();
					this._MAPYC = value;
					this.SendPropertyChanged("MAPYC");
					this.OnMAPYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUDE_PYC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIEUDE_PYC
		{
			get
			{
				return this._TIEUDE_PYC;
			}
			set
			{
				if ((this._TIEUDE_PYC != value))
				{
					this.OnTIEUDE_PYCChanging(value);
					this.SendPropertyChanging();
					this._TIEUDE_PYC = value;
					this.SendPropertyChanged("TIEUDE_PYC");
					this.OnTIEUDE_PYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP_PYC", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYLAP_PYC
		{
			get
			{
				return this._NGAYLAP_PYC;
			}
			set
			{
				if ((this._NGAYLAP_PYC != value))
				{
					this.OnNGAYLAP_PYCChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP_PYC = value;
					this.SendPropertyChanged("NGAYLAP_PYC");
					this.OnNGAYLAP_PYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15)")]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADMYC", DbType="VarChar(15)")]
		public string MADMYC
		{
			get
			{
				return this._MADMYC;
			}
			set
			{
				if ((this._MADMYC != value))
				{
					if (this._DANHMUC_YEUCAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADMYCChanging(value);
					this.SendPropertyChanging();
					this._MADMYC = value;
					this.SendPropertyChanged("MADMYC");
					this.OnMADMYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT_YC", DbType="VarChar(15)")]
		public string MATT_YC
		{
			get
			{
				return this._MATT_YC;
			}
			set
			{
				if ((this._MATT_YC != value))
				{
					if (this._TRANGTHAI_YC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATT_YCChanging(value);
					this.SendPropertyChanging();
					this._MATT_YC = value;
					this.SendPropertyChanged("MATT_YC");
					this.OnMATT_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT_XN", DbType="VarChar(15)")]
		public string MATT_XN
		{
			get
			{
				return this._MATT_XN;
			}
			set
			{
				if ((this._MATT_XN != value))
				{
					if (this._TINHTRANG_XN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATT_XNChanging(value);
					this.SendPropertyChanging();
					this._MATT_XN = value;
					this.SendPropertyChanged("MATT_XN");
					this.OnMATT_XNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKTV", DbType="VarChar(15)")]
		public string MAKTV
		{
			get
			{
				return this._MAKTV;
			}
			set
			{
				if ((this._MAKTV != value))
				{
					if (this._KITHUATVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKTVChanging(value);
					this.SendPropertyChanging();
					this._MAKTV = value;
					this.SendPropertyChanged("MAKTV");
					this.OnMAKTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_PYC", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string MOTA_PYC
		{
			get
			{
				return this._MOTA_PYC;
			}
			set
			{
				if ((this._MOTA_PYC != value))
				{
					this.OnMOTA_PYCChanging(value);
					this.SendPropertyChanging();
					this._MOTA_PYC = value;
					this.SendPropertyChanged("MOTA_PYC");
					this.OnMOTA_PYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(100)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_PYC", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_PYC
		{
			get
			{
				return this._HIENHANH_PYC;
			}
			set
			{
				if ((this._HIENHANH_PYC != value))
				{
					this.OnHIENHANH_PYCChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_PYC = value;
					this.SendPropertyChanged("HIENHANH_PYC");
					this.OnHIENHANH_PYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEU_YC_CTCV", Storage="_CTCVs", ThisKey="MAPYC", OtherKey="MAPYC")]
		public EntitySet<CTCV> CTCVs
		{
			get
			{
				return this._CTCVs;
			}
			set
			{
				this._CTCVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEU_YC_PHIEUXACNHAN_YC", Storage="_PHIEUXACNHAN_YCs", ThisKey="MAPYC", OtherKey="MAPYC")]
		public EntitySet<PHIEUXACNHAN_YC> PHIEUXACNHAN_YCs
		{
			get
			{
				return this._PHIEUXACNHAN_YCs;
			}
			set
			{
				this._PHIEUXACNHAN_YCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUC_YEUCAU_PHIEU_YC", Storage="_DANHMUC_YEUCAU", ThisKey="MADMYC", OtherKey="MADMYC", IsForeignKey=true)]
		public DANHMUC_YEUCAU DANHMUC_YEUCAU
		{
			get
			{
				return this._DANHMUC_YEUCAU.Entity;
			}
			set
			{
				DANHMUC_YEUCAU previousValue = this._DANHMUC_YEUCAU.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUC_YEUCAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUC_YEUCAU.Entity = null;
						previousValue.PHIEU_YCs.Remove(this);
					}
					this._DANHMUC_YEUCAU.Entity = value;
					if ((value != null))
					{
						value.PHIEU_YCs.Add(this);
						this._MADMYC = value.MADMYC;
					}
					else
					{
						this._MADMYC = default(string);
					}
					this.SendPropertyChanged("DANHMUC_YEUCAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEU_YC", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEU_YCs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEU_YCs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KITHUATVIEN_PHIEU_YC", Storage="_KITHUATVIEN", ThisKey="MAKTV", OtherKey="MAKTV", IsForeignKey=true)]
		public KITHUATVIEN KITHUATVIEN
		{
			get
			{
				return this._KITHUATVIEN.Entity;
			}
			set
			{
				KITHUATVIEN previousValue = this._KITHUATVIEN.Entity;
				if (((previousValue != value) 
							|| (this._KITHUATVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KITHUATVIEN.Entity = null;
						previousValue.PHIEU_YCs.Remove(this);
					}
					this._KITHUATVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEU_YCs.Add(this);
						this._MAKTV = value.MAKTV;
					}
					else
					{
						this._MAKTV = default(string);
					}
					this.SendPropertyChanged("KITHUATVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANG_XN_PHIEU_YC", Storage="_TINHTRANG_XN", ThisKey="MATT_XN", OtherKey="MATT_XN", IsForeignKey=true)]
		public TINHTRANG_XN TINHTRANG_XN
		{
			get
			{
				return this._TINHTRANG_XN.Entity;
			}
			set
			{
				TINHTRANG_XN previousValue = this._TINHTRANG_XN.Entity;
				if (((previousValue != value) 
							|| (this._TINHTRANG_XN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTRANG_XN.Entity = null;
						previousValue.PHIEU_YCs.Remove(this);
					}
					this._TINHTRANG_XN.Entity = value;
					if ((value != null))
					{
						value.PHIEU_YCs.Add(this);
						this._MATT_XN = value.MATT_XN;
					}
					else
					{
						this._MATT_XN = default(string);
					}
					this.SendPropertyChanged("TINHTRANG_XN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANGTHAI_YC_PHIEU_YC", Storage="_TRANGTHAI_YC", ThisKey="MATT_YC", OtherKey="MATT_YC", IsForeignKey=true)]
		public TRANGTHAI_YC TRANGTHAI_YC
		{
			get
			{
				return this._TRANGTHAI_YC.Entity;
			}
			set
			{
				TRANGTHAI_YC previousValue = this._TRANGTHAI_YC.Entity;
				if (((previousValue != value) 
							|| (this._TRANGTHAI_YC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANGTHAI_YC.Entity = null;
						previousValue.PHIEU_YCs.Remove(this);
					}
					this._TRANGTHAI_YC.Entity = value;
					if ((value != null))
					{
						value.PHIEU_YCs.Add(this);
						this._MATT_YC = value.MATT_YC;
					}
					else
					{
						this._MATT_YC = default(string);
					}
					this.SendPropertyChanged("TRANGTHAI_YC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTCVs(CTCV entity)
		{
			this.SendPropertyChanging();
			entity.PHIEU_YC = this;
		}
		
		private void detach_CTCVs(CTCV entity)
		{
			this.SendPropertyChanging();
			entity.PHIEU_YC = null;
		}
		
		private void attach_PHIEUXACNHAN_YCs(PHIEUXACNHAN_YC entity)
		{
			this.SendPropertyChanging();
			entity.PHIEU_YC = this;
		}
		
		private void detach_PHIEUXACNHAN_YCs(PHIEUXACNHAN_YC entity)
		{
			this.SendPropertyChanging();
			entity.PHIEU_YC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUXACNHAN_YC")]
	public partial class PHIEUXACNHAN_YC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUXN_YC;
		
		private System.DateTime _NGAYLAP_PXN;
		
		private string _TIEUDE_XN;
		
		private string _MOTA_XN;
		
		private string _MAPYC;
		
		private System.Nullable<bool> _HIENHANH_PXNYC;
		
		private EntityRef<PHIEU_YC> _PHIEU_YC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUXN_YCChanging(string value);
    partial void OnMAPHIEUXN_YCChanged();
    partial void OnNGAYLAP_PXNChanging(System.DateTime value);
    partial void OnNGAYLAP_PXNChanged();
    partial void OnTIEUDE_XNChanging(string value);
    partial void OnTIEUDE_XNChanged();
    partial void OnMOTA_XNChanging(string value);
    partial void OnMOTA_XNChanged();
    partial void OnMAPYCChanging(string value);
    partial void OnMAPYCChanged();
    partial void OnHIENHANH_PXNYCChanging(System.Nullable<bool> value);
    partial void OnHIENHANH_PXNYCChanged();
    #endregion
		
		public PHIEUXACNHAN_YC()
		{
			this._PHIEU_YC = default(EntityRef<PHIEU_YC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUXN_YC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUXN_YC
		{
			get
			{
				return this._MAPHIEUXN_YC;
			}
			set
			{
				if ((this._MAPHIEUXN_YC != value))
				{
					this.OnMAPHIEUXN_YCChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUXN_YC = value;
					this.SendPropertyChanged("MAPHIEUXN_YC");
					this.OnMAPHIEUXN_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP_PXN", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYLAP_PXN
		{
			get
			{
				return this._NGAYLAP_PXN;
			}
			set
			{
				if ((this._NGAYLAP_PXN != value))
				{
					this.OnNGAYLAP_PXNChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP_PXN = value;
					this.SendPropertyChanged("NGAYLAP_PXN");
					this.OnNGAYLAP_PXNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUDE_XN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIEUDE_XN
		{
			get
			{
				return this._TIEUDE_XN;
			}
			set
			{
				if ((this._TIEUDE_XN != value))
				{
					this.OnTIEUDE_XNChanging(value);
					this.SendPropertyChanging();
					this._TIEUDE_XN = value;
					this.SendPropertyChanged("TIEUDE_XN");
					this.OnTIEUDE_XNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_XN", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string MOTA_XN
		{
			get
			{
				return this._MOTA_XN;
			}
			set
			{
				if ((this._MOTA_XN != value))
				{
					this.OnMOTA_XNChanging(value);
					this.SendPropertyChanging();
					this._MOTA_XN = value;
					this.SendPropertyChanged("MOTA_XN");
					this.OnMOTA_XNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPYC", DbType="VarChar(15)")]
		public string MAPYC
		{
			get
			{
				return this._MAPYC;
			}
			set
			{
				if ((this._MAPYC != value))
				{
					if (this._PHIEU_YC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPYCChanging(value);
					this.SendPropertyChanging();
					this._MAPYC = value;
					this.SendPropertyChanged("MAPYC");
					this.OnMAPYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIENHANH_PXNYC", DbType="Bit")]
		public System.Nullable<bool> HIENHANH_PXNYC
		{
			get
			{
				return this._HIENHANH_PXNYC;
			}
			set
			{
				if ((this._HIENHANH_PXNYC != value))
				{
					this.OnHIENHANH_PXNYCChanging(value);
					this.SendPropertyChanging();
					this._HIENHANH_PXNYC = value;
					this.SendPropertyChanged("HIENHANH_PXNYC");
					this.OnHIENHANH_PXNYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEU_YC_PHIEUXACNHAN_YC", Storage="_PHIEU_YC", ThisKey="MAPYC", OtherKey="MAPYC", IsForeignKey=true)]
		public PHIEU_YC PHIEU_YC
		{
			get
			{
				return this._PHIEU_YC.Entity;
			}
			set
			{
				PHIEU_YC previousValue = this._PHIEU_YC.Entity;
				if (((previousValue != value) 
							|| (this._PHIEU_YC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEU_YC.Entity = null;
						previousValue.PHIEUXACNHAN_YCs.Remove(this);
					}
					this._PHIEU_YC.Entity = value;
					if ((value != null))
					{
						value.PHIEUXACNHAN_YCs.Add(this);
						this._MAPYC = value.MAPYC;
					}
					else
					{
						this._MAPYC = default(string);
					}
					this.SendPropertyChanged("PHIEU_YC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTRANG_XN")]
	public partial class TINHTRANG_XN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATT_XN;
		
		private string _TENTT_XN;
		
		private string _MOTA_TTXN;
		
		private EntitySet<PHIEU_YC> _PHIEU_YCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATT_XNChanging(string value);
    partial void OnMATT_XNChanged();
    partial void OnTENTT_XNChanging(string value);
    partial void OnTENTT_XNChanged();
    partial void OnMOTA_TTXNChanging(string value);
    partial void OnMOTA_TTXNChanged();
    #endregion
		
		public TINHTRANG_XN()
		{
			this._PHIEU_YCs = new EntitySet<PHIEU_YC>(new Action<PHIEU_YC>(this.attach_PHIEU_YCs), new Action<PHIEU_YC>(this.detach_PHIEU_YCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT_XN", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATT_XN
		{
			get
			{
				return this._MATT_XN;
			}
			set
			{
				if ((this._MATT_XN != value))
				{
					this.OnMATT_XNChanging(value);
					this.SendPropertyChanging();
					this._MATT_XN = value;
					this.SendPropertyChanged("MATT_XN");
					this.OnMATT_XNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTT_XN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENTT_XN
		{
			get
			{
				return this._TENTT_XN;
			}
			set
			{
				if ((this._TENTT_XN != value))
				{
					this.OnTENTT_XNChanging(value);
					this.SendPropertyChanging();
					this._TENTT_XN = value;
					this.SendPropertyChanged("TENTT_XN");
					this.OnTENTT_XNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_TTXN", DbType="NVarChar(200)")]
		public string MOTA_TTXN
		{
			get
			{
				return this._MOTA_TTXN;
			}
			set
			{
				if ((this._MOTA_TTXN != value))
				{
					this.OnMOTA_TTXNChanging(value);
					this.SendPropertyChanging();
					this._MOTA_TTXN = value;
					this.SendPropertyChanged("MOTA_TTXN");
					this.OnMOTA_TTXNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANG_XN_PHIEU_YC", Storage="_PHIEU_YCs", ThisKey="MATT_XN", OtherKey="MATT_XN")]
		public EntitySet<PHIEU_YC> PHIEU_YCs
		{
			get
			{
				return this._PHIEU_YCs;
			}
			set
			{
				this._PHIEU_YCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANG_XN = this;
		}
		
		private void detach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANG_XN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANGTHAI_YC")]
	public partial class TRANGTHAI_YC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATT_YC;
		
		private string _TENTT_YC;
		
		private string _MOTA_TTYC;
		
		private EntitySet<PHIEU_YC> _PHIEU_YCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATT_YCChanging(string value);
    partial void OnMATT_YCChanged();
    partial void OnTENTT_YCChanging(string value);
    partial void OnTENTT_YCChanged();
    partial void OnMOTA_TTYCChanging(string value);
    partial void OnMOTA_TTYCChanged();
    #endregion
		
		public TRANGTHAI_YC()
		{
			this._PHIEU_YCs = new EntitySet<PHIEU_YC>(new Action<PHIEU_YC>(this.attach_PHIEU_YCs), new Action<PHIEU_YC>(this.detach_PHIEU_YCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT_YC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATT_YC
		{
			get
			{
				return this._MATT_YC;
			}
			set
			{
				if ((this._MATT_YC != value))
				{
					this.OnMATT_YCChanging(value);
					this.SendPropertyChanging();
					this._MATT_YC = value;
					this.SendPropertyChanged("MATT_YC");
					this.OnMATT_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTT_YC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENTT_YC
		{
			get
			{
				return this._TENTT_YC;
			}
			set
			{
				if ((this._TENTT_YC != value))
				{
					this.OnTENTT_YCChanging(value);
					this.SendPropertyChanging();
					this._TENTT_YC = value;
					this.SendPropertyChanged("TENTT_YC");
					this.OnTENTT_YCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_TTYC", DbType="NVarChar(200)")]
		public string MOTA_TTYC
		{
			get
			{
				return this._MOTA_TTYC;
			}
			set
			{
				if ((this._MOTA_TTYC != value))
				{
					this.OnMOTA_TTYCChanging(value);
					this.SendPropertyChanging();
					this._MOTA_TTYC = value;
					this.SendPropertyChanged("MOTA_TTYC");
					this.OnMOTA_TTYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANGTHAI_YC_PHIEU_YC", Storage="_PHIEU_YCs", ThisKey="MATT_YC", OtherKey="MATT_YC")]
		public EntitySet<PHIEU_YC> PHIEU_YCs
		{
			get
			{
				return this._PHIEU_YCs;
			}
			set
			{
				this._PHIEU_YCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.TRANGTHAI_YC = this;
		}
		
		private void detach_PHIEU_YCs(PHIEU_YC entity)
		{
			this.SendPropertyChanging();
			entity.TRANGTHAI_YC = null;
		}
	}
	
	public partial class PROC_KHACHHANGResult
	{
		
		private string _MAKH;
		
		private string _HOTEN_KH;
		
		private string _EMAIL_KH;
		
		private string _SODTH_KH;
		
		private string _TENCHUCVU;
		
		public PROC_KHACHHANGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this._MAKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HOTEN_KH
		{
			get
			{
				return this._HOTEN_KH;
			}
			set
			{
				if ((this._HOTEN_KH != value))
				{
					this._HOTEN_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_KH
		{
			get
			{
				return this._EMAIL_KH;
			}
			set
			{
				if ((this._EMAIL_KH != value))
				{
					this._EMAIL_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODTH_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SODTH_KH
		{
			get
			{
				return this._SODTH_KH;
			}
			set
			{
				if ((this._SODTH_KH != value))
				{
					this._SODTH_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this._TENCHUCVU = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
