#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSERVICE.LQTOSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITSERVICE")]
	public partial class Data_itserviceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertLOAITK(LOAITK instance);
    partial void UpdateLOAITK(LOAITK instance);
    partial void DeleteLOAITK(LOAITK instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    #endregion
		
		public Data_itserviceDataContext() : 
				base(global::ITSERVICE.Properties.Settings.Default.ITSERVICEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itserviceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itserviceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itserviceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_itserviceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<LOAITK> LOAITKs
		{
			get
			{
				return this.GetTable<LOAITK>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROC_KHACHHANG")]
		public ISingleResult<PROC_KHACHHANGResult> PROC_KHACHHANG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PROC_KHACHHANGResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LOGINNAME_AC;
		
		private string _PASSWORD_AC;
		
		private System.Nullable<int> _MALOAI_TK;
		
		private string _MAKH;
		
		private EntityRef<LOAITK> _LOAITK;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOGINNAME_ACChanging(string value);
    partial void OnLOGINNAME_ACChanged();
    partial void OnPASSWORD_ACChanging(string value);
    partial void OnPASSWORD_ACChanged();
    partial void OnMALOAI_TKChanging(System.Nullable<int> value);
    partial void OnMALOAI_TKChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._LOAITK = default(EntityRef<LOAITK>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGINNAME_AC", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LOGINNAME_AC
		{
			get
			{
				return this._LOGINNAME_AC;
			}
			set
			{
				if ((this._LOGINNAME_AC != value))
				{
					this.OnLOGINNAME_ACChanging(value);
					this.SendPropertyChanging();
					this._LOGINNAME_AC = value;
					this.SendPropertyChanged("LOGINNAME_AC");
					this.OnLOGINNAME_ACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_AC", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string PASSWORD_AC
		{
			get
			{
				return this._PASSWORD_AC;
			}
			set
			{
				if ((this._PASSWORD_AC != value))
				{
					this.OnPASSWORD_ACChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_AC = value;
					this.SendPropertyChanged("PASSWORD_AC");
					this.OnPASSWORD_ACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI_TK", DbType="Int")]
		public System.Nullable<int> MALOAI_TK
		{
			get
			{
				return this._MALOAI_TK;
			}
			set
			{
				if ((this._MALOAI_TK != value))
				{
					if (this._LOAITK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAI_TKChanging(value);
					this.SendPropertyChanging();
					this._MALOAI_TK = value;
					this.SendPropertyChanged("MALOAI_TK");
					this.OnMALOAI_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15)")]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITK_ACCOUNT", Storage="_LOAITK", ThisKey="MALOAI_TK", OtherKey="MALOAI_TK", IsForeignKey=true)]
		public LOAITK LOAITK
		{
			get
			{
				return this._LOAITK.Entity;
			}
			set
			{
				LOAITK previousValue = this._LOAITK.Entity;
				if (((previousValue != value) 
							|| (this._LOAITK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITK.Entity = null;
						previousValue.ACCOUNTs.Remove(this);
					}
					this._LOAITK.Entity = value;
					if ((value != null))
					{
						value.ACCOUNTs.Add(this);
						this._MALOAI_TK = value.MALOAI_TK;
					}
					else
					{
						this._MALOAI_TK = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAITK");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_ACCOUNT", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.ACCOUNTs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.ACCOUNTs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITK")]
	public partial class LOAITK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAI_TK;
		
		private string _TENLOAI_TK;
		
		private EntitySet<ACCOUNT> _ACCOUNTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAI_TKChanging(int value);
    partial void OnMALOAI_TKChanged();
    partial void OnTENLOAI_TKChanging(string value);
    partial void OnTENLOAI_TKChanged();
    #endregion
		
		public LOAITK()
		{
			this._ACCOUNTs = new EntitySet<ACCOUNT>(new Action<ACCOUNT>(this.attach_ACCOUNTs), new Action<ACCOUNT>(this.detach_ACCOUNTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI_TK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAI_TK
		{
			get
			{
				return this._MALOAI_TK;
			}
			set
			{
				if ((this._MALOAI_TK != value))
				{
					this.OnMALOAI_TKChanging(value);
					this.SendPropertyChanging();
					this._MALOAI_TK = value;
					this.SendPropertyChanged("MALOAI_TK");
					this.OnMALOAI_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI_TK", DbType="NVarChar(100)")]
		public string TENLOAI_TK
		{
			get
			{
				return this._TENLOAI_TK;
			}
			set
			{
				if ((this._TENLOAI_TK != value))
				{
					this.OnTENLOAI_TKChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI_TK = value;
					this.SendPropertyChanged("TENLOAI_TK");
					this.OnTENLOAI_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITK_ACCOUNT", Storage="_ACCOUNTs", ThisKey="MALOAI_TK", OtherKey="MALOAI_TK")]
		public EntitySet<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this._ACCOUNTs;
			}
			set
			{
				this._ACCOUNTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.LOAITK = this;
		}
		
		private void detach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.LOAITK = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACHUCVU;
		
		private string _TENCHUCVU;
		
		private string _MOTA_CHUCVU;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCVUChanging(string value);
    partial void OnMACHUCVUChanged();
    partial void OnTENCHUCVUChanging(string value);
    partial void OnTENCHUCVUChanged();
    partial void OnMOTA_CHUCVUChanging(string value);
    partial void OnMOTA_CHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this.OnTENCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCVU = value;
					this.SendPropertyChanged("TENCHUCVU");
					this.OnTENCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_CHUCVU", DbType="NVarChar(200)")]
		public string MOTA_CHUCVU
		{
			get
			{
				return this._MOTA_CHUCVU;
			}
			set
			{
				if ((this._MOTA_CHUCVU != value))
				{
					this.OnMOTA_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MOTA_CHUCVU = value;
					this.SendPropertyChanged("MOTA_CHUCVU");
					this.OnMOTA_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MACHUCVU", OtherKey="MACHUCVU")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKH;
		
		private string _HOTEN_KH;
		
		private string _EMAIL_KH;
		
		private string _SODTH_KH;
		
		private string _MACHUCVU;
		
		private EntitySet<ACCOUNT> _ACCOUNTs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnHOTEN_KHChanging(string value);
    partial void OnHOTEN_KHChanged();
    partial void OnEMAIL_KHChanging(string value);
    partial void OnEMAIL_KHChanged();
    partial void OnSODTH_KHChanging(string value);
    partial void OnSODTH_KHChanged();
    partial void OnMACHUCVUChanging(string value);
    partial void OnMACHUCVUChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._ACCOUNTs = new EntitySet<ACCOUNT>(new Action<ACCOUNT>(this.attach_ACCOUNTs), new Action<ACCOUNT>(this.detach_ACCOUNTs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HOTEN_KH
		{
			get
			{
				return this._HOTEN_KH;
			}
			set
			{
				if ((this._HOTEN_KH != value))
				{
					this.OnHOTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_KH = value;
					this.SendPropertyChanged("HOTEN_KH");
					this.OnHOTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_KH
		{
			get
			{
				return this._EMAIL_KH;
			}
			set
			{
				if ((this._EMAIL_KH != value))
				{
					this.OnEMAIL_KHChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_KH = value;
					this.SendPropertyChanged("EMAIL_KH");
					this.OnEMAIL_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODTH_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SODTH_KH
		{
			get
			{
				return this._SODTH_KH;
			}
			set
			{
				if ((this._SODTH_KH != value))
				{
					this.OnSODTH_KHChanging(value);
					this.SendPropertyChanging();
					this._SODTH_KH = value;
					this.SendPropertyChanged("SODTH_KH");
					this.OnSODTH_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="VarChar(15)")]
		public string MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_ACCOUNT", Storage="_ACCOUNTs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this._ACCOUNTs;
			}
			set
			{
				this._ACCOUNTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_KHACHHANG", Storage="_CHUCVU", ThisKey="MACHUCVU", OtherKey="MACHUCVU", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._MACHUCVU = value.MACHUCVU;
					}
					else
					{
						this._MACHUCVU = default(string);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	public partial class PROC_KHACHHANGResult
	{
		
		private string _MAKH;
		
		private string _HOTEN_KH;
		
		private string _EMAIL_KH;
		
		private string _SODTH_KH;
		
		private string _TENCHUCVU;
		
		public PROC_KHACHHANGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this._MAKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HOTEN_KH
		{
			get
			{
				return this._HOTEN_KH;
			}
			set
			{
				if ((this._HOTEN_KH != value))
				{
					this._HOTEN_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_KH
		{
			get
			{
				return this._EMAIL_KH;
			}
			set
			{
				if ((this._EMAIL_KH != value))
				{
					this._EMAIL_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODTH_KH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SODTH_KH
		{
			get
			{
				return this._SODTH_KH;
			}
			set
			{
				if ((this._SODTH_KH != value))
				{
					this._SODTH_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this._TENCHUCVU = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
