CREATE TABLE CHUCVU
(
	MACHUCVU VARCHAR(15) PRIMARY KEY,
	TENCHUCVU NVARCHAR(100) NOT NULL,
	MOTA_CHUCVU NVARCHAR(200) 
)

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(15) PRIMARY KEY,
	HOTEN_KH NVARCHAR(100) NOT NULL,
	EMAIL_KH VARCHAR(100) NOT NULL,
	SODTH_KH VARCHAR(100) NOT NULL,
	MACHUCVU VARCHAR(15) FOREIGN KEY REFERENCES CHUCVU(MACHUCVU)
)

CREATE TABLE LOAITK
(
	MALOAI_TK INT PRIMARY KEY IDENTITY,
	TENLOAI_TK NVARCHAR(100)
)

CREATE TABLE ACCOUNT
(
	LOGINNAME_AC VARCHAR(15) PRIMARY KEY,
	PASSWORD_AC VARCHAR(15) NOT NULL,
	MALOAI_TK INT FOREIGN KEY REFERENCES LOAITK(MALOAI_TK),
	MAKH VARCHAR(15) FOREIGN KEY REFERENCES KHACHHANG(MAKH)
)















CREATE PROC PROC_KHACHHANG
AS
BEGIN
	SELECT KHACHHANG.MAKH,KHACHHANG.HOTEN_KH,KHACHHANG.EMAIL_KH,KHACHHANG.SODTH_KH,CHUCVU.TENCHUCVU
	FROM KHACHHANG,CHUCVU
	WHERE KHACHHANG.MACHUCVU = CHUCVU.MACHUCVU
END
