CREATE DATABASE QLDICHVU_YEUCAU

 CREATE TABLE LOAI_YC
 (
	MALOAI_YC VARCHAR(15) PRIMARY KEY,
	TENLOAI_YC NVARCHAR(100) NOT NULL,
	MOTALOAI_YC NVARCHAR(200)
 )

 CREATE TABLE LINHVUC
 (
	MALV VARCHAR(15) PRIMARY KEY,
	TENLV NVARCHAR(100) NOT NULL
 )

 CREATE TABLE YEUCAU
 (
	MAYC VARCHAR(15) PRIMARY KEY,
	MALOAI_YC VARCHAR(15) FOREIGN KEY REFERENCES LOAI_YC(MALOAI_YC),
	MALV VARCHAR(15) FOREIGN KEY REFERENCES LINHVUC(MALV),
	TIEUDE_YC NVARCHAR(100) NOT NULL,
	MOTA_YC NVARCHAR(200) NOT NULL
 )
 
 CREATE TABLE TRANGTHAI_YC
 (
	MATT_YC VARCHAR(15) PRIMARY KEY,
	TENTT_YC NVARCHAR(50) NOT NULL,
	MOTA_TTYC NVARCHAR(200)
 )

 CREATE TABLE TINHTRANG_XN
 (
	MATT_XN VARCHAR(15) PRIMARY KEY,
	TENTT_XN NVARCHAR(50),
	MOTA_TTXN NVARCHAR(200)
 )

 CREATE TABLE CHUCVU
 (
	MACHUCVU VARCHAR(15) PRIMARY KEY,
	TENCHUCVU NVARCHAR(50) NOT NULL,
	MOTA_CHUCVU NVARCHAR(200) NOT NULL
 )

 CREATE TABLE KHACHHANG
 (
	MAKH VARCHAR(15) PRIMARY KEY,
	HOTEN_KH NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	SODTH_KH VARCHAR(15) NOT NULL,
	MACHUCVU VARCHAR(15) FOREIGN KEY REFERENCES CHUCVU(MACHUCVU)
 )

 CREATE TABLE LOAI_TK
 (
	MALOAI_TK INT PRIMARY KEY,
	TENLOAI_TK NVARCHAR(50) NOT NULL
 )

 CREATE TABLE ACCOUNT
 (
	LOGINNAME VARCHAR(15) PRIMARY KEY,
	PASS_WORD VARCHAR(15) NOT NULL,
	MAKH VARCHAR(15) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MALOAI_TK INT FOREIGN KEY REFERENCES LOAI_TK(MALOAI_TK)
 )

 CREATE TABLE NHOMKTV
 (
	MANHOM VARCHAR(15) PRIMARY KEY,
	TENNHOM NVARCHAR(50) NOT NULL,
	MOTA_NHOM NVARCHAR(200)
 )

 CREATE TABLE KITHUATVIEN
 (
	MAKTV VARCHAR(15) PRIMARY KEY,
	HOTEN_KTV NVARCHAR(50) NOT NULL,
	EMAIL_KTV VARCHAR(50) NOT NULL,
	SODTH_KTV VARCHAR(15) NOT NULL,
	MANHOM VARCHAR(15) FOREIGN KEY REFERENCES NHOMKTV(MANHOM)
 )

 CREATE TABLE PHIEU_YC
 (
	MAPYC VARCHAR(15) PRIMARY KEY,
	NGAYLAP_PHIEU_YC DATETIME NOT NULL,
	MAKH VARCHAR(15) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MAYC VARCHAR(15) FOREIGN KEY REFERENCES YEUCAU(MAYC),
	MATT_YC VARCHAR(15) FOREIGN KEY REFERENCES TRANGTHAI_YC(MATT_YC),
	MATT_XN VARCHAR(15) FOREIGN KEY REFERENCES TINHTRANG_XN(MATT_XN),
	MAKTV VARCHAR(15) FOREIGN KEY REFERENCES KITHUATVIEN(MAKTV),
	MOTA_PYC NVARCHAR(200) NOT NULL,
	DUETIME DATETIME,
	GHICHU NVARCHAR(200)
 )

 CREATE TABLE PHIEUXACNHAN_YC
 (
	MAPHIEUXN_YC VARCHAR(15) PRIMARY KEY,
	NGAYLAP_PXN DATETIME NOT NULL,
	TIEUDE_XN NVARCHAR(100) NOT NULL,
	MOTA_XN NVARCHAR(200),
	MAPYC VARCHAR(15) FOREIGN KEY REFERENCES PHIEU_YC(MAPYC)
 )

 CREATE TABLE LICHSU
 (
	STT INT PRIMARY KEY,
	NGAYCAPNHAT DATETIME NOT NULL,
	MAPYC VARCHAR(15) FOREIGN KEY REFERENCES PHIEU_YC(MAPYC)
 )

	



